// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../lib/db";
import {Providers} from "./providers"; // Adjust path as needed
import IntlProviderWrapper from "./IntlProviderWrapper"; // Assuming it's in app/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Adjust the relative path according to your project structure
  const messages = (await import("../../messages/he.json")).default;

  return (
    <html lang="he" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <IntlProviderWrapper messages={messages} locale="he">
            {children}
          </IntlProviderWrapper>
        </Providers>
      </body>
    </html>
  );
}
